"""Reviewed allowlist of configuration facts safe to project as game rules."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal


@dataclass(frozen=True, slots=True)
class RuleSpec:
    record_id: str
    topic: str
    upstream_path: str
    label: str
    value_type: Literal["number"]
    unit: str | None = None


# Keep this intentionally narrow. A field enters the public projection only
# after its meaning and unit have been verified against official behavior.
RULES: tuple[RuleSpec, ...] = (
    RuleSpec(
        "player.max_hunger", "player", "user.maxHunger", "Maximum hunger", "number", "hunger_points"
    ),
    RuleSpec(
        "player.max_energy", "player", "user.maxEnergy", "Maximum energy", "number", "energy_points"
    ),
    RuleSpec("player.daily_xp", "player", "user.dailyXp", "Daily XP limit", "number", "xp"),
    RuleSpec(
        "player.construction_energy_cost",
        "player",
        "user.constructionEnergyCost",
        "Energy cost per construction action",
        "number",
        "energy_points",
    ),
    RuleSpec(
        "combat.rounds_to_win",
        "combat",
        "battle.roundsToWin",
        "Rounds required to win a battle",
        "number",
        "rounds",
    ),
    RuleSpec(
        "combat.health_cost",
        "combat",
        "battle.healthCost",
        "Health cost per attempted hit",
        "number",
        "health_points",
    ),
    RuleSpec(
        "combat.points_to_win_round",
        "combat",
        "battle.pointsToWinRound",
        "Points required to win a round",
        "number",
        "points",
    ),
    RuleSpec(
        "combat.patriotic_bonus",
        "combat",
        "battle.patrioticBonusPercent",
        "Patriotic battle bonus",
        "number",
        "percentage_points",
    ),
    RuleSpec(
        "companies.construction_cost_increment",
        "companies",
        "company.constructionCostIncreasePerCompany",
        "Construction cost increase per company",
        "number",
        "concrete_units",
    ),
    RuleSpec(
        "companies.deposit_resource_bonus",
        "companies",
        "company.depositResourceBonus",
        "Configured deposit resource bonus",
        "number",
    ),
    RuleSpec(
        "workers.fidelity_production_bonus",
        "workers",
        "worker.fidelityProductionBonusPercent",
        "Worker fidelity production bonus",
        "number",
        "percentage_points",
    ),
    RuleSpec(
        "military_units.max_owned",
        "military_units",
        "mu.maxOwnedMus",
        "Maximum owned military units",
        "number",
        "units",
    ),
    RuleSpec(
        "military_units.health_per_help",
        "military_units",
        "mu.healthPerHelp",
        "Health restored per military unit help",
        "number",
        "health_points",
    ),
    RuleSpec(
        "politics.candidate_min_level",
        "politics",
        "election.candidateMinLevel",
        "Minimum candidate level",
        "number",
        "player_levels",
    ),
    RuleSpec(
        "politics.vote_min_level",
        "politics",
        "election.voteMinLevel",
        "Minimum voter level",
        "number",
        "player_levels",
    ),
    RuleSpec(
        "world.max_resistance",
        "world",
        "region.maxResistance",
        "Maximum resistance",
        "number",
        "resistance_points",
    ),
    RuleSpec(
        "world.min_daily_resistance",
        "world",
        "region.minDailyResistance",
        "Minimum daily resistance",
        "number",
        "resistance_points",
    ),
    RuleSpec(
        "world.max_daily_resistance",
        "world",
        "region.maxDailyResistance",
        "Maximum daily resistance",
        "number",
        "resistance_points",
    ),
    RuleSpec(
        "missions.daily_xp",
        "missions",
        "mission.reward.daily.xp",
        "Daily mission XP reward",
        "number",
        "xp",
    ),
    RuleSpec(
        "missions.daily_completion_xp",
        "missions",
        "mission.reward.daily.xpWhenFinished",
        "Daily mission completion XP reward",
        "number",
        "xp",
    ),
    RuleSpec(
        "missions.daily_money",
        "missions",
        "mission.reward.daily.money",
        "Daily mission money reward",
        "number",
        "money",
    ),
    RuleSpec(
        "missions.daily_cases",
        "missions",
        "mission.reward.daily.cases",
        "Daily mission case reward",
        "number",
        "cases",
    ),
    RuleSpec(
        "missions.weekly_xp",
        "missions",
        "mission.reward.weekly.xp",
        "Weekly mission XP reward",
        "number",
        "xp",
    ),
    RuleSpec(
        "missions.weekly_completion_xp",
        "missions",
        "mission.reward.weekly.xpWhenFinished",
        "Weekly mission completion XP reward",
        "number",
        "xp",
    ),
    RuleSpec(
        "missions.weekly_money",
        "missions",
        "mission.reward.weekly.money",
        "Weekly mission money reward",
        "number",
        "money",
    ),
    RuleSpec(
        "missions.weekly_cases",
        "missions",
        "mission.reward.weekly.cases",
        "Weekly mission case reward",
        "number",
        "cases",
    ),
    RuleSpec(
        "missions.monthly_xp",
        "missions",
        "mission.reward.monthly.xp",
        "Monthly mission XP reward",
        "number",
        "xp",
    ),
    RuleSpec(
        "missions.monthly_completion_xp",
        "missions",
        "mission.reward.monthly.xpWhenFinished",
        "Monthly mission completion XP reward",
        "number",
        "xp",
    ),
    RuleSpec(
        "missions.monthly_money",
        "missions",
        "mission.reward.monthly.money",
        "Monthly mission money reward",
        "number",
        "money",
    ),
    RuleSpec(
        "missions.monthly_cases",
        "missions",
        "mission.reward.monthly.cases",
        "Monthly mission case reward",
        "number",
        "cases",
    ),
)

# Additional scalar fields confirmed in the 2026-10-04 official snapshot.
RULES += tuple(
    RuleSpec(*entry)
    for entry in (
        (
            "player.max_construction_points",
            "player",
            "user.maxConstructionPoints",
            "Maximum construction points",
            "number",
            "construction_points",
        ),
        (
            "player.inactive_after_days",
            "player",
            "user.isInactiveAfterDays",
            "Days before inactive status",
            "number",
            "days",
        ),
        (
            "player.energy_cost_per_action",
            "player",
            "user.energyCostPerAction",
            "Energy cost per action",
            "number",
            "energy_points",
        ),
        (
            "player.reset_skills_cost_per_point",
            "player",
            "user.resetSkillsCostPerPoint",
            "Skill reset cost per point",
            "number",
            None,
        ),
        (
            "player.reset_skill_cooldown_days",
            "player",
            "user.resetSkillDaysCooldown",
            "Skill reset cooldown",
            "number",
            "days",
        ),
        (
            "player.market_min_level",
            "player",
            "user.marketMinLevel",
            "Minimum level for market access",
            "number",
            "player_levels",
        ),
        (
            "player.donation_min_level",
            "player",
            "user.donationMinLevel",
            "Minimum level for donations",
            "number",
            "player_levels",
        ),
        (
            "player.chat_min_level",
            "player",
            "user.chatMinLevel",
            "Minimum level for chat",
            "number",
            "player_levels",
        ),
        (
            "player.active_citizen_min_level",
            "player",
            "user.activeCitizenMinLevel",
            "Minimum active citizen level",
            "number",
            "player_levels",
        ),
        (
            "combat.max_rounds",
            "combat",
            "battle.maxRounds",
            "Maximum battle rounds",
            "number",
            "rounds",
        ),
        (
            "combat.country_order_bonus",
            "combat",
            "battle.countryOrderBonusPercent",
            "Country order damage bonus",
            "number",
            "percentage_points",
        ),
        (
            "combat.military_unit_order_bonus",
            "combat",
            "battle.muOrderBonusPercent",
            "Military unit order damage bonus",
            "number",
            "percentage_points",
        ),
        (
            "combat.alliance_damage_bonus",
            "combat",
            "battle.allianceDamagesBonusPercent",
            "Alliance damage bonus",
            "number",
            "percentage_points",
        ),
        (
            "combat.enemy_damage_bonus",
            "combat",
            "battle.enemyDamagesBonusPercent",
            "Enemy damage bonus",
            "number",
            "percentage_points",
        ),
        (
            "combat.order_money_cost",
            "combat",
            "battle.setOrderMoneyCost",
            "Order change cost",
            "number",
            "money",
        ),
        (
            "companies.move_cost",
            "companies",
            "company.moveCost",
            "Company move cost",
            "number",
            "money",
        ),
        (
            "companies.change_item_cost",
            "companies",
            "company.changeItemCost",
            "Company item change cost",
            "number",
            "money",
        ),
        (
            "companies.destruction_value_percent",
            "companies",
            "company.destructionValuePercent",
            "Company destruction value",
            "number",
            "percentage_points",
        ),
        (
            "workers.max_fidelity",
            "workers",
            "worker.maxFidelity",
            "Maximum worker fidelity",
            "number",
            "fidelity_points",
        ),
        (
            "military_units.construction_cost",
            "military_units",
            "mu.constructionCost",
            "Military unit construction cost",
            "number",
            "money",
        ),
        (
            "military_units.move_cost",
            "military_units",
            "mu.moveCost",
            "Military unit move cost",
            "number",
            "money",
        ),
        (
            "military_units.help_cooldown_hours",
            "military_units",
            "mu.helpCooldownHours",
            "Military unit help cooldown",
            "number",
            "hours",
        ),
        (
            "military_units.help_value",
            "military_units",
            "mu.helpValue",
            "Military unit help value",
            "number",
            None,
        ),
        (
            "politics.candidate_duration_hours",
            "politics",
            "election.candidateDurationHours",
            "Candidate period",
            "number",
            "hours",
        ),
        (
            "politics.vote_duration_hours",
            "politics",
            "election.electionVoteDurationHours",
            "Election voting period",
            "number",
            "hours",
        ),
        (
            "politics.citizenship_change_wait_days",
            "politics",
            "election.voteMinDaysSinceCitizenshipChange",
            "Wait after citizenship change before voting",
            "number",
            "days",
        ),
        (
            "world.home_move_concrete_cost",
            "world",
            "region.homeMoveConcreteCost",
            "Cost to move home",
            "number",
            "concrete_units",
        ),
        (
            "world.free_home_travel_cooldown_hours",
            "world",
            "region.freeTravelHomeCooldownHours",
            "Free home travel cooldown",
            "number",
            "hours",
        ),
        (
            "world.citizen_income_tax_percent",
            "world",
            "region.citizenIncomeTaxPercent",
            "Citizen income tax",
            "number",
            "percentage_points",
        ),
        (
            "world.transfer_cooldown_days",
            "world",
            "region.transferDaysCooldown",
            "Region transfer cooldown",
            "number",
            "days",
        ),
        (
            "world.liberation_cooldown_days",
            "world",
            "region.liberationDaysCooldown",
            "Liberation cooldown",
            "number",
            "days",
        ),
        (
            "world.non_aggression_after_liberation_hours",
            "world",
            "region.nonAggressionHoursAfterLiberation",
            "Non-aggression period after liberation",
            "number",
            "hours",
        ),
        (
            "world.resource_depletion_hourly_percent",
            "world",
            "region.depleteHourlyPercent",
            "Hourly resource depletion",
            "number",
            "percentage_points",
        ),
        (
            "missions.starting_xp",
            "missions",
            "mission.reward.starting.xp",
            "Starting mission XP reward",
            "number",
            "xp",
        ),
        (
            "missions.starting_completion_xp",
            "missions",
            "mission.reward.starting.xpWhenFinished",
            "Starting mission completion XP reward",
            "number",
            "xp",
        ),
        (
            "missions.starting_money",
            "missions",
            "mission.reward.starting.money",
            "Starting mission money reward",
            "number",
            "money",
        ),
        (
            "missions.starting_cases",
            "missions",
            "mission.reward.starting.cases",
            "Starting mission case reward",
            "number",
            "cases",
        ),
    )
)

TABLE_RULES: tuple[tuple[str, str, str, str, str], ...] = (
    # topic, table path, record prefix, key column, value column
    ("combat", "battle.tickPoints", "combat.tick_points", "damage_threshold", "points"),
    ("missions", "mission.rerollMissionCost", "missions.reroll_cost", "rerolls", "cost"),
)

__all__ = ["RULES", "TABLE_RULES", "RuleSpec"]
